//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuahsi.sync.Odm.Server {
    
    
    #region SyncService: Configuration and setup
    public class OdmScopeSyncService : Microsoft.Synchronization.Services.SyncService<OdmScopeOfflineEntities> {
        
        public static void InitializeService(Microsoft.Synchronization.Services.ISyncServiceConfiguration config) {
            // TODO: MUST set these values
            // config.ServerConnectionString = "connection string here";
            // config.SetEnableScope("scope name goes here");
            // 
            // 
            // TODO: Optional.
            // config.SetDefaultSyncSerializationFormat(Microsoft.Synchronization.Services.SyncSerializationFormat.ODataJson);
            // config.SetConflictResolutionPolicy(Microsoft.Synchronization.Services.ConflictResolutionPolicy.ServerWins);
            // 
            // 
            // Note: The scope has specified a non dbo schema for creating sync tables. Removing this line will cause requests from new clients to fail.
            config.SetSyncObjectSchema("dbo");
        }
    }
    #endregion
}
