<?xml version="1.0" encoding="utf-8"?>
<Database Name="LittleBearRiverODM" Class="ODMDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=waterdata.usu.edu;Initial Catalog=LittleBearRiverODM;Persist Security Info=True;User ID=TSA" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LittleBearRiverODMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataValues" Member="DataValues">
    <Type Name="DataValue">
      <Column Name="ValueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataValue" Member="DataValue1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ValueAccuracy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LocalDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UTCOffset" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateTimeUTC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VariableID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OffsetValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OffsetTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CensorCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QualifierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MethodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SampleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DerivedFromID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QualityControlLevelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DataValue_DerivedFrom" Member="DerivedFroms" ThisKey="ValueID" OtherKey="ValueID" Type="DerivedFrom" />
      <Association Name="Source_DataValue" Member="Source" ThisKey="SourceID" OtherKey="SourceID" Type="Source" IsForeignKey="true" />
      <Association Name="Method_DataValue" Member="Method" ThisKey="MethodID" OtherKey="MethodID" Type="Method" IsForeignKey="true" />
      <Association Name="QualityControlLevel_DataValue" Member="QualityControlLevel" ThisKey="QualityControlLevelID" OtherKey="QualityControlLevelID" Type="QualityControlLevel" IsForeignKey="true" />
      <Association Name="Variable_DataValue" Member="Variable" ThisKey="VariableID" OtherKey="VariableID" Type="Variable" IsForeignKey="true" />
      <Association Name="Sample_DataValue" Member="Sample" ThisKey="SampleID" OtherKey="SampleID" Type="Sample" IsForeignKey="true" />
      <Association Name="Qualifier_DataValue" Member="Qualifier" ThisKey="QualifierID" OtherKey="QualifierID" Type="Qualifier" IsForeignKey="true" />
      <Association Name="Site_DataValue" Member="Site" ThisKey="SiteID" OtherKey="SiteID" Type="Site" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sources" Member="Sources">
    <Type Name="Source">
      <Column Name="SourceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Organization" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SourceDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SourceLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MetadataID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Source_DataValue" Member="DataValues" ThisKey="SourceID" OtherKey="SourceID" Type="DataValue" />
    </Type>
  </Table>
  <Table Name="dbo.Units" Member="Units">
    <Type Name="Unit">
      <Column Name="UnitsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UnitsName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UnitsType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UnitsAbbreviation" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Unit_Variable" Member="Variables" ThisKey="UnitsID" OtherKey="VariableUnitsID" Type="Variable" />
      <Association Name="Unit_Variable1" Member="Variables1" ThisKey="UnitsID" OtherKey="TimeUnitsID" Type="Variable" />
    </Type>
  </Table>
  <Table Name="dbo.SeriesCatalog" Member="TimeSeries">
    <Type Name="TimeSeries">
      <Column Name="SeriesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VariableID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VariableUnitsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeUnitsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QualityControlLevelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BeginDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BeginDateTimeUTC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTimeUTC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValueCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Methods" Member="Methods">
    <Type Name="Method">
      <Column Name="MethodID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MethodDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MethodLink" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Method_DataValue" Member="DataValues" ThisKey="MethodID" OtherKey="MethodID" Type="DataValue" />
    </Type>
  </Table>
  <Table Name="dbo.QualityControlLevels" Member="QualityControlLevels">
    <Type Name="QualityControlLevel">
      <Column Name="QualityControlLevelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Definition" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Explanation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="QualityControlLevel_DataValue" Member="DataValues" ThisKey="QualityControlLevelID" OtherKey="QualityControlLevelID" Type="DataValue" />
    </Type>
  </Table>
  <Table Name="dbo.Variables" Member="Variables">
    <Type Name="Variable">
      <Column Name="VariableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VariableCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VariableName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VariableUnitsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeUnitsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Variable_DataValue" Member="DataValues" ThisKey="VariableID" OtherKey="VariableID" Type="DataValue" />
      <Association Name="Unit_Variable" Member="Unit" ThisKey="VariableUnitsID" OtherKey="UnitsID" Type="Unit" IsForeignKey="true" />
      <Association Name="Unit_Variable1" Member="Unit1" ThisKey="TimeUnitsID" OtherKey="UnitsID" Type="Unit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Samples" Member="Samples">
    <Type Name="Sample">
      <Column Name="SampleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SampleType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LabSampleCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LabMethodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sample_DataValue" Member="DataValues" ThisKey="SampleID" OtherKey="SampleID" Type="DataValue" />
    </Type>
  </Table>
  <Table Name="dbo.Qualifiers" Member="Qualifiers">
    <Type Name="Qualifier">
      <Column Name="QualifierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QualifierCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QualifierDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Qualifier_DataValue" Member="DataValues" ThisKey="QualifierID" OtherKey="QualifierID" Type="DataValue" />
    </Type>
  </Table>
  <Table Name="dbo.DerivedFrom" Member="DerivedFroms">
    <Type Name="DerivedFrom">
      <Column Name="DerivedFromID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ValueID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DataValue_DerivedFrom" Member="DataValue" ThisKey="ValueID" OtherKey="ValueID" Type="DataValue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sites" Member="Sites">
    <Type Name="Site">
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LatLongDatumID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Elevation_m" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VerticalDatum" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LocalX" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LocalY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LocalProjectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PosAccuracy_m" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="County" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Site_DataValue" Member="DataValues" ThisKey="SiteID" OtherKey="SiteID" Type="DataValue" />
    </Type>
  </Table>
</Database>