//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace WaterOneFlow.Schema.v1 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cuahsi.org/waterML/")]
    [System.Xml.Serialization.XmlRootAttribute("variables", Namespace="http://www.cuahsi.org/waterML/", IsNullable=false)]
    public partial class VariablesType {
        
        private VariablesTypeVariable[] variableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variable")]
        public VariablesTypeVariable[] variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class VariablesTypeVariable {
        
        private string variableIDField;
        
        private string unitsField;
        
        private string vocabularyField;
        
        private string oidField;
        
        private System.DateTime metadatatimeField;
        
        private bool metadatatimeFieldSpecified;
        
        /// <remarks/>
        public string variableID {
            get {
                return this.variableIDField;
            }
            set {
                this.variableIDField = value;
            }
        }
        
        /// <remarks/>
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vocabulary {
            get {
                return this.vocabularyField;
            }
            set {
                this.vocabularyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime metadatatime {
            get {
                return this.metadatatimeField;
            }
            set {
                this.metadatatimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metadatatimeSpecified {
            get {
                return this.metadatatimeFieldSpecified;
            }
            set {
                this.metadatatimeFieldSpecified = value;
            }
        }
    }
}
