//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cuahsi.sync.Odm.Client {
    
    
    public class OdmScopeOfflineEntityBase : object, Microsoft.Synchronization.ClientServices.IOfflineEntity {
        
        private Microsoft.Synchronization.ClientServices.OfflineEntityMetadata _serviceMetadata;
        
        public OdmScopeOfflineEntityBase() {
            ServiceMetadata = new Microsoft.Synchronization.ClientServices.OfflineEntityMetadata();
        }
        
        public virtual Microsoft.Synchronization.ClientServices.OfflineEntityMetadata ServiceMetadata {
            get {
                return _serviceMetadata;
            }
            set {
                if ((value == null)) {
                    throw new System.ArgumentNullException("value");
                }
                _serviceMetadata = value;
            }
        }
    }
    
    public partial class GeneralCategoryCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class DataTypeCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class Units : OdmScopeOfflineEntityBase {
        
        private int _UnitsID;
        
        private string _UnitsName;
        
        private string _UnitsType;
        
        private string _UnitsAbbreviation;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int UnitsID {
            get {
                return _UnitsID;
            }
            set {
                _UnitsID = value;
            }
        }
        
        public string UnitsName {
            get {
                return _UnitsName;
            }
            set {
                _UnitsName = value;
            }
        }
        
        public string UnitsType {
            get {
                return _UnitsType;
            }
            set {
                _UnitsType = value;
            }
        }
        
        public string UnitsAbbreviation {
            get {
                return _UnitsAbbreviation;
            }
            set {
                _UnitsAbbreviation = value;
            }
        }
    }
    
    public partial class SpatialReferences : OdmScopeOfflineEntityBase {
        
        private int _SpatialReferenceID;
        
        private System.Nullable<int> _SRSID;
        
        private string _SRSName;
        
        private System.Nullable<bool> _IsGeographic;
        
        private string _Notes;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int SpatialReferenceID {
            get {
                return _SpatialReferenceID;
            }
            set {
                _SpatialReferenceID = value;
            }
        }
        
        public System.Nullable<int> SRSID {
            get {
                return _SRSID;
            }
            set {
                _SRSID = value;
            }
        }
        
        public string SRSName {
            get {
                return _SRSName;
            }
            set {
                _SRSName = value;
            }
        }
        
        public System.Nullable<bool> IsGeographic {
            get {
                return _IsGeographic;
            }
            set {
                _IsGeographic = value;
            }
        }
        
        public string Notes {
            get {
                return _Notes;
            }
            set {
                _Notes = value;
            }
        }
    }
    
    public partial class ValueTypeCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class Sources : OdmScopeOfflineEntityBase {
        
        private int _SourceID;
        
        private string _Organization;
        
        private string _SourceDescription;
        
        private string _SourceLink;
        
        private string _ContactName;
        
        private string _Phone;
        
        private string _Email;
        
        private string _Address;
        
        private string _City;
        
        private string _State;
        
        private string _ZipCode;
        
        private string _Citation;
        
        private int _MetadataID;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int SourceID {
            get {
                return _SourceID;
            }
            set {
                _SourceID = value;
            }
        }
        
        public string Organization {
            get {
                return _Organization;
            }
            set {
                _Organization = value;
            }
        }
        
        public string SourceDescription {
            get {
                return _SourceDescription;
            }
            set {
                _SourceDescription = value;
            }
        }
        
        public string SourceLink {
            get {
                return _SourceLink;
            }
            set {
                _SourceLink = value;
            }
        }
        
        public string ContactName {
            get {
                return _ContactName;
            }
            set {
                _ContactName = value;
            }
        }
        
        public string Phone {
            get {
                return _Phone;
            }
            set {
                _Phone = value;
            }
        }
        
        public string Email {
            get {
                return _Email;
            }
            set {
                _Email = value;
            }
        }
        
        public string Address {
            get {
                return _Address;
            }
            set {
                _Address = value;
            }
        }
        
        public string City {
            get {
                return _City;
            }
            set {
                _City = value;
            }
        }
        
        public string State {
            get {
                return _State;
            }
            set {
                _State = value;
            }
        }
        
        public string ZipCode {
            get {
                return _ZipCode;
            }
            set {
                _ZipCode = value;
            }
        }
        
        public string Citation {
            get {
                return _Citation;
            }
            set {
                _Citation = value;
            }
        }
        
        public int MetadataID {
            get {
                return _MetadataID;
            }
            set {
                _MetadataID = value;
            }
        }
    }
    
    public partial class TopicCategoryCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class VariableNameCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class SpeciationCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class OffsetTypes : OdmScopeOfflineEntityBase {
        
        private int _OffsetTypeID;
        
        private int _OffsetUnitsID;
        
        private string _OffsetDescription;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int OffsetTypeID {
            get {
                return _OffsetTypeID;
            }
            set {
                _OffsetTypeID = value;
            }
        }
        
        public int OffsetUnitsID {
            get {
                return _OffsetUnitsID;
            }
            set {
                _OffsetUnitsID = value;
            }
        }
        
        public string OffsetDescription {
            get {
                return _OffsetDescription;
            }
            set {
                _OffsetDescription = value;
            }
        }
    }
    
    public partial class CensorCodeCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class DataValues : OdmScopeOfflineEntityBase {
        
        private int _ValueID;
        
        private double _DataValue;
        
        private System.Nullable<double> _ValueAccuracy;
        
        private System.DateTime _LocalDateTime;
        
        private double _UTCOffset;
        
        private System.DateTime _DateTimeUTC;
        
        private int _SiteID;
        
        private int _VariableID;
        
        private System.Nullable<double> _OffsetValue;
        
        private System.Nullable<int> _OffsetTypeID;
        
        private string _CensorCode;
        
        private System.Nullable<int> _QualifierID;
        
        private int _MethodID;
        
        private int _SourceID;
        
        private System.Nullable<int> _SampleID;
        
        private System.Nullable<int> _DerivedFromID;
        
        private int _QualityControlLevelID;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int ValueID {
            get {
                return _ValueID;
            }
            set {
                _ValueID = value;
            }
        }
        
        public double DataValue {
            get {
                return _DataValue;
            }
            set {
                _DataValue = value;
            }
        }
        
        public System.Nullable<double> ValueAccuracy {
            get {
                return _ValueAccuracy;
            }
            set {
                _ValueAccuracy = value;
            }
        }
        
        public System.DateTime LocalDateTime {
            get {
                return _LocalDateTime;
            }
            set {
                _LocalDateTime = value;
            }
        }
        
        public double UTCOffset {
            get {
                return _UTCOffset;
            }
            set {
                _UTCOffset = value;
            }
        }
        
        public System.DateTime DateTimeUTC {
            get {
                return _DateTimeUTC;
            }
            set {
                _DateTimeUTC = value;
            }
        }
        
        public int SiteID {
            get {
                return _SiteID;
            }
            set {
                _SiteID = value;
            }
        }
        
        public int VariableID {
            get {
                return _VariableID;
            }
            set {
                _VariableID = value;
            }
        }
        
        public System.Nullable<double> OffsetValue {
            get {
                return _OffsetValue;
            }
            set {
                _OffsetValue = value;
            }
        }
        
        public System.Nullable<int> OffsetTypeID {
            get {
                return _OffsetTypeID;
            }
            set {
                _OffsetTypeID = value;
            }
        }
        
        public string CensorCode {
            get {
                return _CensorCode;
            }
            set {
                _CensorCode = value;
            }
        }
        
        public System.Nullable<int> QualifierID {
            get {
                return _QualifierID;
            }
            set {
                _QualifierID = value;
            }
        }
        
        public int MethodID {
            get {
                return _MethodID;
            }
            set {
                _MethodID = value;
            }
        }
        
        public int SourceID {
            get {
                return _SourceID;
            }
            set {
                _SourceID = value;
            }
        }
        
        public System.Nullable<int> SampleID {
            get {
                return _SampleID;
            }
            set {
                _SampleID = value;
            }
        }
        
        public System.Nullable<int> DerivedFromID {
            get {
                return _DerivedFromID;
            }
            set {
                _DerivedFromID = value;
            }
        }
        
        public int QualityControlLevelID {
            get {
                return _QualityControlLevelID;
            }
            set {
                _QualityControlLevelID = value;
            }
        }
    }
    
    public partial class QualityControlLevels : OdmScopeOfflineEntityBase {
        
        private int _QualityControlLevelID;
        
        private string _QualityControlLevelCode;
        
        private string _Definition;
        
        private string _Explanation;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int QualityControlLevelID {
            get {
                return _QualityControlLevelID;
            }
            set {
                _QualityControlLevelID = value;
            }
        }
        
        public string QualityControlLevelCode {
            get {
                return _QualityControlLevelCode;
            }
            set {
                _QualityControlLevelCode = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
        
        public string Explanation {
            get {
                return _Explanation;
            }
            set {
                _Explanation = value;
            }
        }
    }
    
    public partial class SampleMediumCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class SeriesCatalog : OdmScopeOfflineEntityBase {
        
        private int _SeriesID;
        
        private System.Nullable<int> _SiteID;
        
        private string _SiteCode;
        
        private string _SiteName;
        
        private System.Nullable<int> _VariableID;
        
        private string _VariableCode;
        
        private string _VariableName;
        
        private string _Speciation;
        
        private System.Nullable<int> _VariableUnitsID;
        
        private string _VariableUnitsName;
        
        private string _SampleMedium;
        
        private string _ValueType;
        
        private System.Nullable<double> _TimeSupport;
        
        private System.Nullable<int> _TimeUnitsID;
        
        private string _TimeUnitsName;
        
        private string _DataType;
        
        private string _GeneralCategory;
        
        private System.Nullable<int> _MethodID;
        
        private string _MethodDescription;
        
        private System.Nullable<int> _SourceID;
        
        private string _Organization;
        
        private string _SourceDescription;
        
        private string _Citation;
        
        private System.Nullable<int> _QualityControlLevelID;
        
        private string _QualityControlLevelCode;
        
        private System.Nullable<System.DateTime> _BeginDateTime;
        
        private System.Nullable<System.DateTime> _EndDateTime;
        
        private System.Nullable<System.DateTime> _BeginDateTimeUTC;
        
        private System.Nullable<System.DateTime> _EndDateTimeUTC;
        
        private System.Nullable<int> _ValueCount;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int SeriesID {
            get {
                return _SeriesID;
            }
            set {
                _SeriesID = value;
            }
        }
        
        public System.Nullable<int> SiteID {
            get {
                return _SiteID;
            }
            set {
                _SiteID = value;
            }
        }
        
        public string SiteCode {
            get {
                return _SiteCode;
            }
            set {
                _SiteCode = value;
            }
        }
        
        public string SiteName {
            get {
                return _SiteName;
            }
            set {
                _SiteName = value;
            }
        }
        
        public System.Nullable<int> VariableID {
            get {
                return _VariableID;
            }
            set {
                _VariableID = value;
            }
        }
        
        public string VariableCode {
            get {
                return _VariableCode;
            }
            set {
                _VariableCode = value;
            }
        }
        
        public string VariableName {
            get {
                return _VariableName;
            }
            set {
                _VariableName = value;
            }
        }
        
        public string Speciation {
            get {
                return _Speciation;
            }
            set {
                _Speciation = value;
            }
        }
        
        public System.Nullable<int> VariableUnitsID {
            get {
                return _VariableUnitsID;
            }
            set {
                _VariableUnitsID = value;
            }
        }
        
        public string VariableUnitsName {
            get {
                return _VariableUnitsName;
            }
            set {
                _VariableUnitsName = value;
            }
        }
        
        public string SampleMedium {
            get {
                return _SampleMedium;
            }
            set {
                _SampleMedium = value;
            }
        }
        
        public string ValueType {
            get {
                return _ValueType;
            }
            set {
                _ValueType = value;
            }
        }
        
        public System.Nullable<double> TimeSupport {
            get {
                return _TimeSupport;
            }
            set {
                _TimeSupport = value;
            }
        }
        
        public System.Nullable<int> TimeUnitsID {
            get {
                return _TimeUnitsID;
            }
            set {
                _TimeUnitsID = value;
            }
        }
        
        public string TimeUnitsName {
            get {
                return _TimeUnitsName;
            }
            set {
                _TimeUnitsName = value;
            }
        }
        
        public string DataType {
            get {
                return _DataType;
            }
            set {
                _DataType = value;
            }
        }
        
        public string GeneralCategory {
            get {
                return _GeneralCategory;
            }
            set {
                _GeneralCategory = value;
            }
        }
        
        public System.Nullable<int> MethodID {
            get {
                return _MethodID;
            }
            set {
                _MethodID = value;
            }
        }
        
        public string MethodDescription {
            get {
                return _MethodDescription;
            }
            set {
                _MethodDescription = value;
            }
        }
        
        public System.Nullable<int> SourceID {
            get {
                return _SourceID;
            }
            set {
                _SourceID = value;
            }
        }
        
        public string Organization {
            get {
                return _Organization;
            }
            set {
                _Organization = value;
            }
        }
        
        public string SourceDescription {
            get {
                return _SourceDescription;
            }
            set {
                _SourceDescription = value;
            }
        }
        
        public string Citation {
            get {
                return _Citation;
            }
            set {
                _Citation = value;
            }
        }
        
        public System.Nullable<int> QualityControlLevelID {
            get {
                return _QualityControlLevelID;
            }
            set {
                _QualityControlLevelID = value;
            }
        }
        
        public string QualityControlLevelCode {
            get {
                return _QualityControlLevelCode;
            }
            set {
                _QualityControlLevelCode = value;
            }
        }
        
        public System.Nullable<System.DateTime> BeginDateTime {
            get {
                return _BeginDateTime;
            }
            set {
                _BeginDateTime = value;
            }
        }
        
        public System.Nullable<System.DateTime> EndDateTime {
            get {
                return _EndDateTime;
            }
            set {
                _EndDateTime = value;
            }
        }
        
        public System.Nullable<System.DateTime> BeginDateTimeUTC {
            get {
                return _BeginDateTimeUTC;
            }
            set {
                _BeginDateTimeUTC = value;
            }
        }
        
        public System.Nullable<System.DateTime> EndDateTimeUTC {
            get {
                return _EndDateTimeUTC;
            }
            set {
                _EndDateTimeUTC = value;
            }
        }
        
        public System.Nullable<int> ValueCount {
            get {
                return _ValueCount;
            }
            set {
                _ValueCount = value;
            }
        }
    }
    
    public partial class Variables : OdmScopeOfflineEntityBase {
        
        private int _VariableID;
        
        private string _VariableCode;
        
        private string _VariableName;
        
        private string _Speciation;
        
        private int _VariableUnitsID;
        
        private string _SampleMedium;
        
        private string _ValueType;
        
        private bool _IsRegular;
        
        private double _TimeSupport;
        
        private int _TimeUnitsID;
        
        private string _DataType;
        
        private string _GeneralCategory;
        
        private double _NoDataValue;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int VariableID {
            get {
                return _VariableID;
            }
            set {
                _VariableID = value;
            }
        }
        
        public string VariableCode {
            get {
                return _VariableCode;
            }
            set {
                _VariableCode = value;
            }
        }
        
        public string VariableName {
            get {
                return _VariableName;
            }
            set {
                _VariableName = value;
            }
        }
        
        public string Speciation {
            get {
                return _Speciation;
            }
            set {
                _Speciation = value;
            }
        }
        
        public int VariableUnitsID {
            get {
                return _VariableUnitsID;
            }
            set {
                _VariableUnitsID = value;
            }
        }
        
        public string SampleMedium {
            get {
                return _SampleMedium;
            }
            set {
                _SampleMedium = value;
            }
        }
        
        public string ValueType {
            get {
                return _ValueType;
            }
            set {
                _ValueType = value;
            }
        }
        
        public bool IsRegular {
            get {
                return _IsRegular;
            }
            set {
                _IsRegular = value;
            }
        }
        
        public double TimeSupport {
            get {
                return _TimeSupport;
            }
            set {
                _TimeSupport = value;
            }
        }
        
        public int TimeUnitsID {
            get {
                return _TimeUnitsID;
            }
            set {
                _TimeUnitsID = value;
            }
        }
        
        public string DataType {
            get {
                return _DataType;
            }
            set {
                _DataType = value;
            }
        }
        
        public string GeneralCategory {
            get {
                return _GeneralCategory;
            }
            set {
                _GeneralCategory = value;
            }
        }
        
        public double NoDataValue {
            get {
                return _NoDataValue;
            }
            set {
                _NoDataValue = value;
            }
        }
    }
    
    public partial class ISOMetadata : OdmScopeOfflineEntityBase {
        
        private int _MetadataID;
        
        private string _TopicCategory;
        
        private string _Title;
        
        private string _Abstract;
        
        private string _ProfileVersion;
        
        private string _MetadataLink;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int MetadataID {
            get {
                return _MetadataID;
            }
            set {
                _MetadataID = value;
            }
        }
        
        public string TopicCategory {
            get {
                return _TopicCategory;
            }
            set {
                _TopicCategory = value;
            }
        }
        
        public string Title {
            get {
                return _Title;
            }
            set {
                _Title = value;
            }
        }
        
        public string Abstract {
            get {
                return _Abstract;
            }
            set {
                _Abstract = value;
            }
        }
        
        public string ProfileVersion {
            get {
                return _ProfileVersion;
            }
            set {
                _ProfileVersion = value;
            }
        }
        
        public string MetadataLink {
            get {
                return _MetadataLink;
            }
            set {
                _MetadataLink = value;
            }
        }
    }
    
    public partial class LabMethods : OdmScopeOfflineEntityBase {
        
        private int _LabMethodID;
        
        private string _LabName;
        
        private string _LabOrganization;
        
        private string _LabMethodName;
        
        private string _LabMethodDescription;
        
        private string _LabMethodLink;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int LabMethodID {
            get {
                return _LabMethodID;
            }
            set {
                _LabMethodID = value;
            }
        }
        
        public string LabName {
            get {
                return _LabName;
            }
            set {
                _LabName = value;
            }
        }
        
        public string LabOrganization {
            get {
                return _LabOrganization;
            }
            set {
                _LabOrganization = value;
            }
        }
        
        public string LabMethodName {
            get {
                return _LabMethodName;
            }
            set {
                _LabMethodName = value;
            }
        }
        
        public string LabMethodDescription {
            get {
                return _LabMethodDescription;
            }
            set {
                _LabMethodDescription = value;
            }
        }
        
        public string LabMethodLink {
            get {
                return _LabMethodLink;
            }
            set {
                _LabMethodLink = value;
            }
        }
    }
    
    public partial class Methods : OdmScopeOfflineEntityBase {
        
        private int _MethodID;
        
        private string _MethodDescription;
        
        private string _MethodLink;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int MethodID {
            get {
                return _MethodID;
            }
            set {
                _MethodID = value;
            }
        }
        
        public string MethodDescription {
            get {
                return _MethodDescription;
            }
            set {
                _MethodDescription = value;
            }
        }
        
        public string MethodLink {
            get {
                return _MethodLink;
            }
            set {
                _MethodLink = value;
            }
        }
    }
    
    public partial class SampleTypeCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class Qualifiers : OdmScopeOfflineEntityBase {
        
        private int _QualifierID;
        
        private string _QualifierCode;
        
        private string _QualifierDescription;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int QualifierID {
            get {
                return _QualifierID;
            }
            set {
                _QualifierID = value;
            }
        }
        
        public string QualifierCode {
            get {
                return _QualifierCode;
            }
            set {
                _QualifierCode = value;
            }
        }
        
        public string QualifierDescription {
            get {
                return _QualifierDescription;
            }
            set {
                _QualifierDescription = value;
            }
        }
    }
    
    public partial class Samples : OdmScopeOfflineEntityBase {
        
        private int _SampleID;
        
        private string _SampleType;
        
        private string _LabSampleCode;
        
        private int _LabMethodID;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int SampleID {
            get {
                return _SampleID;
            }
            set {
                _SampleID = value;
            }
        }
        
        public string SampleType {
            get {
                return _SampleType;
            }
            set {
                _SampleType = value;
            }
        }
        
        public string LabSampleCode {
            get {
                return _LabSampleCode;
            }
            set {
                _LabSampleCode = value;
            }
        }
        
        public int LabMethodID {
            get {
                return _LabMethodID;
            }
            set {
                _LabMethodID = value;
            }
        }
    }
    
    public partial class VerticalDatumCV : OdmScopeOfflineEntityBase {
        
        private string _Term;
        
        private string _Definition;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Term {
            get {
                return _Term;
            }
            set {
                _Term = value;
            }
        }
        
        public string Definition {
            get {
                return _Definition;
            }
            set {
                _Definition = value;
            }
        }
    }
    
    public partial class Sites : OdmScopeOfflineEntityBase {
        
        private int _SiteID;
        
        private string _SiteCode;
        
        private string _SiteName;
        
        private double _Latitude;
        
        private double _Longitude;
        
        private int _LatLongDatumID;
        
        private System.Nullable<double> _Elevation_m;
        
        private string _VerticalDatum;
        
        private System.Nullable<double> _LocalX;
        
        private System.Nullable<double> _LocalY;
        
        private System.Nullable<int> _LocalProjectionID;
        
        private System.Nullable<double> _PosAccuracy_m;
        
        private string _State;
        
        private string _County;
        
        private string _Comments;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int SiteID {
            get {
                return _SiteID;
            }
            set {
                _SiteID = value;
            }
        }
        
        public string SiteCode {
            get {
                return _SiteCode;
            }
            set {
                _SiteCode = value;
            }
        }
        
        public string SiteName {
            get {
                return _SiteName;
            }
            set {
                _SiteName = value;
            }
        }
        
        public double Latitude {
            get {
                return _Latitude;
            }
            set {
                _Latitude = value;
            }
        }
        
        public double Longitude {
            get {
                return _Longitude;
            }
            set {
                _Longitude = value;
            }
        }
        
        public int LatLongDatumID {
            get {
                return _LatLongDatumID;
            }
            set {
                _LatLongDatumID = value;
            }
        }
        
        public System.Nullable<double> Elevation_m {
            get {
                return _Elevation_m;
            }
            set {
                _Elevation_m = value;
            }
        }
        
        public string VerticalDatum {
            get {
                return _VerticalDatum;
            }
            set {
                _VerticalDatum = value;
            }
        }
        
        public System.Nullable<double> LocalX {
            get {
                return _LocalX;
            }
            set {
                _LocalX = value;
            }
        }
        
        public System.Nullable<double> LocalY {
            get {
                return _LocalY;
            }
            set {
                _LocalY = value;
            }
        }
        
        public System.Nullable<int> LocalProjectionID {
            get {
                return _LocalProjectionID;
            }
            set {
                _LocalProjectionID = value;
            }
        }
        
        public System.Nullable<double> PosAccuracy_m {
            get {
                return _PosAccuracy_m;
            }
            set {
                _PosAccuracy_m = value;
            }
        }
        
        public string State {
            get {
                return _State;
            }
            set {
                _State = value;
            }
        }
        
        public string County {
            get {
                return _County;
            }
            set {
                _County = value;
            }
        }
        
        public string Comments {
            get {
                return _Comments;
            }
            set {
                _Comments = value;
            }
        }
    }
}
