//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.cuahsi.org/waterML/", IsNullable=false)]
public partial class Networks {
    
    private NetworksNetwork[] networkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Network")]
    public NetworksNetwork[] Network {
        get {
            return this.networkField;
        }
        set {
            this.networkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class NetworksNetwork {
    
    private int networkIDField;
    
    private string organizationField;
    
    private string networkNameField;
    
    private string longNetworkNameField;
    
    private string uRLField;
    
    private int stationNumberField;
    
    private bool stationNumberFieldSpecified;
    
    private System.DateTime obsStartDateField;
    
    private bool obsStartDateFieldSpecified;
    
    private System.DateTime obsEndDateField;
    
    private bool obsEndDateFieldSpecified;
    
    private System.DateTime lastUpdateField;
    
    private bool lastUpdateFieldSpecified;
    
    private string contactField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NetworkID {
        get {
            return this.networkIDField;
        }
        set {
            this.networkIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NetworkName {
        get {
            return this.networkNameField;
        }
        set {
            this.networkNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LongNetworkName {
        get {
            return this.longNetworkNameField;
        }
        set {
            this.longNetworkNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string URL {
        get {
            return this.uRLField;
        }
        set {
            this.uRLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int StationNumber {
        get {
            return this.stationNumberField;
        }
        set {
            this.stationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StationNumberSpecified {
        get {
            return this.stationNumberFieldSpecified;
        }
        set {
            this.stationNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ObsStartDate {
        get {
            return this.obsStartDateField;
        }
        set {
            this.obsStartDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ObsStartDateSpecified {
        get {
            return this.obsStartDateFieldSpecified;
        }
        set {
            this.obsStartDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ObsEndDate {
        get {
            return this.obsEndDateField;
        }
        set {
            this.obsEndDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ObsEndDateSpecified {
        get {
            return this.obsEndDateFieldSpecified;
        }
        set {
            this.obsEndDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime LastUpdate {
        get {
            return this.lastUpdateField;
        }
        set {
            this.lastUpdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastUpdateSpecified {
        get {
            return this.lastUpdateFieldSpecified;
        }
        set {
            this.lastUpdateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
}
